import type { JournalArticle } from "@/lib/types";

export const journal: JournalArticle[] = [
  {
    slug: "how-to-identify-a-real-gemstone",
    title: "How to identify a genuine gemstone",
    dek: "A house primer: tests that belong in a laboratory, and signs you can actually see.",
    category: "learn",
    date: "2026-03-12",
    readMinutes: 8,
    relatedSpecies: ["ruby", "sapphire", "emerald"],
    body: "",
    seo: {
      title: "How to identify a genuine gemstone | Kalpa Journal",
      description:
        "What certification, inclusions and origin actually tell you — without folklore dressed as science.",
    },
  },
  {
    slug: "natural-versus-synthetic-gemstones",
    title: "Natural versus laboratory-grown",
    dek: "Two honest materials. The difference is geology, time, and how we price them.",
    category: "learn",
    date: "2026-02-02",
    readMinutes: 6,
    relatedSpecies: ["sapphire", "diamond", "ruby"],
    body: "",
    seo: {
      title: "Natural vs laboratory-grown gemstones | Kalpa Journal",
      description: "How Kalpa distinguishes natural and laboratory-grown stones — and why both are labelled.",
    },
  },
  {
    slug: "what-gemstone-certification-means",
    title: "What gemstone certification means",
    dek: "A report is a description, not a blessing. How to read one without being read by it.",
    category: "learn",
    date: "2026-01-18",
    readMinutes: 7,
    relatedSpecies: ["diamond", "ruby", "sapphire"],
    body: "",
    seo: {
      title: "What gemstone certification means | Kalpa Journal",
      description: "GIA, GRS, Gübelin and the limits of paper — a calm guide to laboratory reports.",
    },
  },
  {
    slug: "kashmir-sapphire",
    title: "Kashmir, and the problem of velvet",
    dek: "A locality that became a colour. Why we refuse to borrow the name.",
    category: "stories",
    date: "2025-11-09",
    readMinutes: 9,
    relatedSpecies: ["sapphire"],
    body: "",
    seo: {
      title: "Kashmir sapphire | Kalpa Journal",
      description: "The history of Kashmir sapphire, and why Kalpa will not misattribute velvet.",
    },
  },
  {
    slug: "vedic-astrology-gemstones",
    title: "Vedic astrology and the nine gems",
    dek: "Navaratna as a cultural system — planetary stones without medical or financial claims.",
    category: "astrology",
    date: "2025-10-21",
    readMinutes: 10,
    relatedSpecies: ["ruby", "pearl", "emerald", "diamond"],
    body: "",
    seo: {
      title: "Vedic astrology gemstones | Kalpa Journal",
      description: "How the navaratna system maps planets to gems — presented as tradition, not science.",
    },
  },
  {
    slug: "understanding-carat",
    title: "Understanding carat",
    dek: "Weight is not size. Size is not beauty. A short essay on a misunderstood number.",
    category: "learn",
    date: "2025-09-04",
    readMinutes: 5,
    relatedSpecies: ["diamond", "ruby"],
    body: "",
    seo: {
      title: "Understanding carat | Kalpa Journal",
      description: "What a carat measures, and what it does not, in the selection of a gemstone.",
    },
  },
  {
    slug: "burmese-ruby",
    title: "The Mogok tract",
    dek: "Marble, chromium, and a red that fluoresces. A locality with a long memory.",
    category: "stories",
    date: "2025-08-16",
    readMinutes: 8,
    relatedSpecies: ["ruby"],
    body: "",
    seo: {
      title: "Burmese ruby and the Mogok tract | Kalpa Journal",
      description: "The geology and cultural history of Mogok ruby, without myth-making.",
    },
  },
  {
    slug: "gemstone-treatments-explained",
    title: "Treatments, explained",
    dek: "Heat, oil, fracture filling. What is customary, what must be said, what we will not sell.",
    category: "learn",
    date: "2025-07-02",
    readMinutes: 8,
    relatedSpecies: ["emerald", "sapphire", "ruby"],
    body: "",
    seo: {
      title: "Gemstone treatments explained | Kalpa Journal",
      description: "A plain account of common gemstone treatments and Kalpa’s disclosure standard.",
    },
  },
];
